package com.fungle.brume.report;

/**
 * Immutable record representing a single natural-language observation about a Brume run.
 *
 * <p>Insights are generated by {@link InsightGenerator} after the pipeline completes and
 * stored in {@link ComparisonSummary}. They give operators a plain-text interpretation of
 * the comparison metrics without any prior knowledge of the schema.
 *
 * @param level    severity level of the observation
 * @param message  human-readable explanation in French
 * @param category grouping key — either a table name (for per-table observations) or
 *                 {@code "Global"} (for cross-table summary observations)
 */
public record Insight(Level level, String message, String category) {

    /**
     * Severity levels for an {@link Insight}.
     */
    public enum Level {
        /** Everything looks correct — informational message. */
        OK,
        /** A potential issue worth reviewing, but not a hard failure. */
        WARN,
        /** A definitive error: data was lost or could not be inserted. */
        ERROR
    }

    /**
     * Returns the single Unicode icon character that represents this insight's level.
     *
     * @return {@code "✓"} for OK, {@code "⚠"} for WARN, {@code "✗"} for ERROR
     */
    public String icon() {
        return switch (level) {
            case OK    -> "✓";
            case WARN  -> "⚠";
            case ERROR -> "✗";
        };
    }
}

