package com.fungle.brume.config.schema;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fungle.brume.config.model.AnonymizationConfig;
import com.fungle.brume.config.model.AnonymizerConfig;
import com.fungle.brume.config.model.ColumnConfig;
import com.fungle.brume.config.model.ColumnReference;
import com.fungle.brume.config.model.ExtractionConfig;
import com.fungle.brume.config.model.JsonPathConfig;
import com.fungle.brume.config.model.LinkedColumnsConfig;
import com.fungle.brume.config.model.SemanticType;
import com.fungle.brume.config.model.Strategy;
import com.fungle.brume.config.model.TableAnonymizationConfig;
import com.fungle.brume.config.model.TableExtractionConfig;
import com.github.victools.jsonschema.generator.Option;
import com.github.victools.jsonschema.generator.OptionPreset;
import com.github.victools.jsonschema.generator.SchemaGenerator;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfig;
import com.github.victools.jsonschema.generator.SchemaGeneratorConfigBuilder;
import com.github.victools.jsonschema.generator.SchemaVersion;
import com.github.victools.jsonschema.module.jackson.JacksonModule;

import java.util.Map;

/**
 * Generates the JSON Schema (draft 2020-12) for {@code config.yaml}.
 *
 * <p>The schema is rooted on {@link AnonymizerConfig} and recursively covers all nested
 * records and enums under {@code com.fungle.brume.config.model}. Property names are
 * emitted in SNAKE_CASE to match {@link com.fungle.brume.config.ConfigLoader}.
 *
 * <p>Descriptions are sourced from {@link #TYPE_DESCRIPTIONS} and {@link #FIELD_DESCRIPTIONS}
 * — short, user-facing strings rendered in IDE hovers and autocomplete (rather than the
 * developer-oriented Javadoc on the records themselves).
 *
 * <p>The output is intended to be checked in at {@code src/main/resources/config.schema.json}
 * and re-generated by {@link ConfigSchemaDriftTest} on every build.
 */
public final class ConfigSchemaGenerator {

    public static final String SCHEMA_TITLE = "Brume anonymizer config";

    /**
     * Public version of the schema, bumped on breaking changes to {@link AnonymizerConfig}
     * or its nested records (#36 / E2). Follows SemVer-like semantics restricted to
     * MAJOR.MINOR : MAJOR bumps when a field is removed, renamed, or changes meaning ;
     * MINOR bumps when fields or enum values are added. The {@code BRUME_REGEN_SCHEMA=1}
     * anti-drift loop catches every change — the developer who runs it is the one who
     * decides whether the change deserves a MAJOR or a MINOR bump and updates this constant
     * accordingly. Once a release is git-tagged, the corresponding schema is immutable for
     * that tag. A future {@code config-v2.0.schema.json} physical file would only be
     * introduced at the next MAJOR bump (V1 ships a single file under {@code
     * config.schema.json} to keep the convention simple).
     */
    public static final String SCHEMA_VERSION = "1.0";

    public static final String SCHEMA_ID =
            "https://github.com/fungle/brume/blob/main/src/main/resources/config-v"
                    + SCHEMA_VERSION + ".schema.json";

    private static final Map<Class<?>, String> TYPE_DESCRIPTIONS = Map.ofEntries(
            Map.entry(ExtractionConfig.class,
                    "Which tables to read from the source database and how — FK propagation depth, batch sizes, and per-table filters."),
            Map.entry(AnonymizationConfig.class,
                    "Cross-table column linkages and per-table, per-column anonymization rules."),
            Map.entry(TableExtractionConfig.class,
                    "One table to extract, with an optional WHERE filter applied during the source read."),
            Map.entry(TableAnonymizationConfig.class,
                    "Anonymization rules for all columns of one table."),
            Map.entry(ColumnConfig.class,
                    "Anonymization rule for a single column. The 'type' field is required when strategy=FAKE."),
            Map.entry(ColumnReference.class,
                    "Reference to a column by (table, column) name. Used inside linked_columns."),
            Map.entry(JsonPathConfig.class,
                    "Anonymization rule for one path inside a JSONB column."),
            Map.entry(LinkedColumnsConfig.class,
                    "Group of columns across tables that must receive the same anonymized value (e.g. users.email and audit_logs.user_email)."),
            Map.entry(Strategy.class,
                    "Anonymization strategy. FAKE = deterministic fake (requires type). "
                            + "MASK = partial masking. HASH = SHA-256 one-way. NULLIFY = null. "
                            + "KEEP = copy unchanged. FPE_ID = format-preserving for numeric IDs. "
                            + "FPE_UUID = format-preserving for UUIDs."),
            Map.entry(SemanticType.class,
                    "Semantic type of a column value — drives fake data generation (FAKE) "
                            + "or masking pattern (MASK). JSONB requires a non-empty json_paths list.")
    );

    private static final Map<Class<?>, Map<String, String>> FIELD_DESCRIPTIONS = Map.ofEntries(
            Map.entry(AnonymizerConfig.class, Map.ofEntries(
                    Map.entry("extraction", "Source-side extraction rules: which tables to read and with which filters."),
                    Map.entry("anonymization", "Anonymization rules applied to extracted rows before they reach the target.")
            )),
            Map.entry(ExtractionConfig.class, Map.ofEntries(
                    Map.entry("fkDepth", "Maximum FK parent levels to resolve automatically when a row's parent is missing from the extracted set. 1 = direct parents only. Default: 3."),
                    Map.entry("fetchSize", "JDBC cursor fetch size used during streaming reads from the source. Default: 1000."),
                    Map.entry("batchSize", "Number of rows per INSERT batch on the target. Default: 1000."),
                    Map.entry("chunkSize", "Number of rows processed in memory per streaming chunk. Default: 10000."),
                    Map.entry("tables", "Tables to extract. Each entry may carry an optional WHERE filter. Tables not listed are only extracted if they are FK parents of a listed table.")
            )),
            Map.entry(TableExtractionConfig.class, Map.ofEntries(
                    Map.entry("table", "Unqualified table name (the schema is configured separately via replication.schema in application.yaml)."),
                    Map.entry("filter", "Optional SQL WHERE clause snippet, without the WHERE keyword. Null or blank = all rows. Security validation: see README § Configuration > extraction.")
            )),
            Map.entry(AnonymizationConfig.class, Map.ofEntries(
                    Map.entry("linkedColumns", "Cross-table column groups that must produce the same anonymized value for the same input."),
                    Map.entry("tables", "Per-table anonymization rules (one entry per table; columns listed inside).")
            )),
            Map.entry(LinkedColumnsConfig.class, Map.ofEntries(
                    Map.entry("semanticKey", "Unique identifier for this cross-table linkage. Used as part of the substitution-dictionary key. Example: \"user_email\"."),
                    Map.entry("columns", "Table/column pairs that share this semantic meaning. Minimum two entries for the linkage to be meaningful.")
            )),
            Map.entry(ColumnReference.class, Map.ofEntries(
                    Map.entry("table", "Table name (unqualified, same schema as the rest of the config)."),
                    Map.entry("column", "Column name within that table.")
            )),
            Map.entry(TableAnonymizationConfig.class, Map.ofEntries(
                    Map.entry("table", "Unqualified table name."),
                    Map.entry("columns", "Ordered list of per-column anonymization rules.")
            )),
            Map.entry(ColumnConfig.class, Map.ofEntries(
                    Map.entry("name", "Column name as it appears in the database schema."),
                    Map.entry("strategy", "Anonymization strategy to apply to this column."),
                    Map.entry("type", "Semantic type — required when strategy=FAKE, optional/ignored for HASH/NULLIFY/KEEP/FPE_ID/FPE_UUID. Use JSONB to anonymize specific paths inside a JSON column (see json_paths)."),
                    Map.entry("jsonPaths", "Per-path anonymization rules for this column. Required when type=JSONB; ignored otherwise.")
            )),
            Map.entry(JsonPathConfig.class, Map.ofEntries(
                    Map.entry("path", "JSONPath expression starting with $ — e.g. \"$.user.email\" or \"$.metadata.session.token\"."),
                    Map.entry("type", "Semantic type of the targeted JSON field."),
                    Map.entry("strategy", "Anonymization strategy applied to that field.")
            ))
    );

    private ConfigSchemaGenerator() {
    }

    public static String generate() {
        SchemaGeneratorConfigBuilder builder = new SchemaGeneratorConfigBuilder(
                SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON)
                .with(Option.FORBIDDEN_ADDITIONAL_PROPERTIES_BY_DEFAULT)
                .with(Option.DEFINITIONS_FOR_ALL_OBJECTS)
                .with(Option.NULLABLE_FIELDS_BY_DEFAULT)
                .with(new JacksonModule());

        builder.forFields().withPropertyNameOverrideResolver(
                field -> toSnakeCase(field.getName()));

        builder.forFields().withDescriptionResolver(field -> {
            Map<String, String> classFields = FIELD_DESCRIPTIONS.get(field.getDeclaringType().getErasedType());
            return classFields == null ? null : classFields.get(field.getName());
        });

        builder.forTypesInGeneral().withDescriptionResolver(
                scope -> TYPE_DESCRIPTIONS.get(scope.getType().getErasedType()));

        SchemaGeneratorConfig config = builder.build();
        SchemaGenerator generator = new SchemaGenerator(config);
        JsonNode rawSchema = generator.generateSchema(AnonymizerConfig.class);

        ObjectNode schema = (ObjectNode) rawSchema;
        backfillFieldDescriptions(schema);
        ObjectNode decorated = decorate(schema);

        ObjectMapper mapper = new ObjectMapper();
        try {
            return mapper.writerWithDefaultPrettyPrinter().writeValueAsString(decorated) + "\n";
        } catch (Exception e) {
            throw new IllegalStateException("Failed to serialize generated schema", e);
        }
    }

    private static ObjectNode decorate(ObjectNode schema) {
        ObjectMapper mapper = new ObjectMapper();
        ObjectNode out = mapper.createObjectNode();
        out.put("$schema", SchemaVersion.DRAFT_2020_12.getIdentifier());
        out.put("$id", SCHEMA_ID);
        out.put("title", SCHEMA_TITLE);
        out.put("description",
                "JSON Schema for the user-facing Brume anonymizer config file "
                        + "(commonly named config.yaml). Bound to com.fungle.brume.config.model.AnonymizerConfig.");
        // #36 / E2 — explicit schema version. Custom top-level field, ignored by
        // JSON Schema validators (which only understand $schema, $id, $defs, etc.).
        // Bumped according to the SemVer-like rules documented on SCHEMA_VERSION.
        out.put("version", SCHEMA_VERSION);
        schema.fields().forEachRemaining(entry -> out.set(entry.getKey(), entry.getValue()));
        return out;
    }

    /**
     * Walks each {@code $defs/<TypeName>} entry of the generated schema and ensures every
     * property in {@link #FIELD_DESCRIPTIONS} carries its description. Also drops the
     * cosmetic duplicate descriptions that victools sometimes injects inside an array's
     * {@code items} sub-schema.
     *
     * <p>This is a workaround for two victools 4.37 quirks observed on records:
     * primitive-typed fields (int) and some {@code List<>} fields are not visited by
     * {@code withDescriptionResolver}; conversely some are visited twice and the inner
     * {@code items} schema receives a redundant copy of the description.
     */
    private static void backfillFieldDescriptions(ObjectNode schema) {
        Map<String, Class<?>> typeNameToClass = Map.ofEntries(
                Map.entry("AnonymizerConfig", AnonymizerConfig.class),
                Map.entry("ExtractionConfig", ExtractionConfig.class),
                Map.entry("AnonymizationConfig", AnonymizationConfig.class),
                Map.entry("TableExtractionConfig", TableExtractionConfig.class),
                Map.entry("TableAnonymizationConfig", TableAnonymizationConfig.class),
                Map.entry("ColumnConfig", ColumnConfig.class),
                Map.entry("ColumnReference", ColumnReference.class),
                Map.entry("JsonPathConfig", JsonPathConfig.class),
                Map.entry("LinkedColumnsConfig", LinkedColumnsConfig.class)
        );

        backfillObject(schema, AnonymizerConfig.class);

        JsonNode defs = schema.get("$defs");
        if (defs == null) {
            return;
        }
        defs.fields().forEachRemaining(entry -> {
            Class<?> owningClass = typeNameToClass.get(entry.getKey());
            if (owningClass != null && entry.getValue().isObject()) {
                backfillObject((ObjectNode) entry.getValue(), owningClass);
            }
        });
    }

    private static void backfillObject(ObjectNode typeSchema, Class<?> owningClass) {
        Map<String, String> fieldDescs = FIELD_DESCRIPTIONS.get(owningClass);
        if (fieldDescs == null) {
            return;
        }
        JsonNode props = typeSchema.get("properties");
        if (props == null || !props.isObject()) {
            return;
        }
        fieldDescs.forEach((javaFieldName, description) -> {
            String snakeName = toSnakeCase(javaFieldName);
            JsonNode propNode = props.get(snakeName);
            if (propNode instanceof ObjectNode propObj) {
                if (!propObj.has("description")) {
                    propObj.put("description", description);
                }
                JsonNode items = propObj.get("items");
                if (items instanceof ObjectNode itemsObj && itemsObj.has("description")) {
                    itemsObj.remove("description");
                }
            }
        });
    }

    static String toSnakeCase(String camelCase) {
        if (camelCase == null || camelCase.isEmpty()) {
            return camelCase;
        }
        StringBuilder sb = new StringBuilder(camelCase.length() + 4);
        for (int i = 0; i < camelCase.length(); i++) {
            char c = camelCase.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                sb.append('_');
            }
            sb.append(Character.toLowerCase(c));
        }
        return sb.toString();
    }
}
